### ISSUE TITLE
Make responses configurable through TOML

### ISSUE THREAD

**Issue by mre** [mre/teapot#1]
## Example

```toml
[[route]]
matches = "/"
response = "static/index.html"

[[route]]
matches = "/:usr"
response = "static/hello.html"

[fallback]
response = "teapot"
```

The responses would receive the matching template variables.
So `static/hello.html` would get a `{{usr}}` variable.

teapot would be a [well-known preset ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418). 😉 

## Collaboration

I'm probably not gonna add the functionality in the foreseeable future, but it could be a fun
exercise for someone looking for a little project.
So if someone wants to work on this, please feel free to add a comment here.

Here's how I would do it:

Add [axum](https://github.com/tokio-rs/axum) or another web framework as a dependency.
Write a [serde-toml](https://docs.rs/toml/latest/toml/)-based parser for the routing format.
Set up dynamic routes from the TOML config in the web-framework. (I don't know if this is possible with Axum)

Open for other solutions, though.

## Credits

In https://github.com/mre/teapot/commit/7d271ba40ebdc6330e0edf1f49ce86ff5a805597#r89222702 @aszlig and me started a discussion about server responses. I decided to move it here so that the idea doesn't get lost.

[binserve](https://github.com/mufeedvh/binserve) has such functionality, even though I prefer TOML as a configuration language. They also don't provide any fallback route (or presets) as far as I can tell.
